apiVersion: velero.io/v1
kind: Restore
metadata:
  generateName: aap-restore-
  namespace: openshift-adp
  labels:
    app: ansible-automation-platform
    component: postgres
spec:
  excludedResources:
  - ansibleautomationplatformbackups.aap.ansible.com
  - ansibleautomationplatformrestores.aap.ansible.com
  - ansibleautomationplatforms.aap.ansible.com
  - events.events.k8s.io
  - deployment.apps
  - rbac.authorization.k8s.io
  - RoleBinding
  - rolebindings
  - Role
  - roles
  - Route
  - events
  - jobs
  - Lease
  - DaemonSet
  - ControllerRevision
  - ClusterServiceVersion
  - ControllerRevision
  - Endpoints
  - EndpointSlice
  - HorizontalPodAutoscaler
  - ReplicaSet
  - authorization.openshift.io
  hooks:
    resources:
      - includedNamespaces:
          - ansible-automation-platform
        labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/component
              operator: In
              values:
                - database
            - key: app.kubernetes.io/managed-by
              operator: In
              values:
                - automationcontroller-operator
        postHooks:
          - exec:
              command:
                - "/bin/bash"
                - "-c"
                - /usr/bin/zcat /var/lib/pgsql/data/backup/pg_dumpall.gz | /usr/bin/psql -U postgres
              container: postgres
              execTimeout: 180s
              waitForReady: true
              onError: Fail
        name: pg_restore
  includedNamespaces:
    - ansible-automation-platform
  backupName: ${BACKUPID}
